#ifndef WEBCOLORLIST
#define WEBCOLORLIST
//ここで定義される色はWebで使えるとされるブラウザ定義のWebColor一覧です。
//出典:WEB色見本 原色大辞典 - HTML Color Names
//     http://www.colordic.org/

struct WEBCOLOR
{
	unsigned int Black;
	unsigned int Aliceblue;
	unsigned int Darkcyan;
	unsigned int Lightyellow;
	unsigned int Coral;
	unsigned int Dimgray;
	unsigned int Lavender;
	unsigned int Teal;
	unsigned int Lightgoldenrodyellow;
	unsigned int Tomato;
	unsigned int Gray;
	unsigned int Lightsteelblue;
	unsigned int Darkslategray;
	unsigned int Lemonchiffon;
	unsigned int Orangered;
	unsigned int Darkgray;
	unsigned int Lightslategray;
	unsigned int Darkgreen;
	unsigned int Wheat;
	unsigned int Red;
	unsigned int Silver;
	unsigned int Slategray;
	unsigned int Green;
	unsigned int Burlywood;
	unsigned int Crimson;
	unsigned int Lightgrey;
	unsigned int Steelblue;
	unsigned int Forestgreen;
	unsigned int Tan;
	unsigned int Mediumvioletred;
	unsigned int Gainsboro;
	unsigned int Royalblue;
	unsigned int Seagreen;
	unsigned int Khaki;
	unsigned int Deeppink;
	unsigned int Whitesmoke;
	unsigned int Midnightblue;
	unsigned int Mediumseagreen;
	unsigned int Yellow;
	unsigned int Hotpink;
	unsigned int White;
	unsigned int Navy;
	unsigned int Mediumaquamarine;
	unsigned int Gold;
	unsigned int Palevioletred;
	unsigned int Snow;
	unsigned int Darkblue;
	unsigned int Darkseagreen;
	unsigned int Orange;
	unsigned int Pink;
	unsigned int Ghostwhite;
	unsigned int Mediumblue;
	unsigned int Aquamarine;
	unsigned int Sandybrown;
	unsigned int Lightpink;
	unsigned int Floralwhite;
	unsigned int Blue;
	unsigned int Palegreen;
	unsigned int Darkorange;
	unsigned int Thistle;
	unsigned int Linen;
	unsigned int Dodgerblue;
	unsigned int Lightgreen;
	unsigned int Goldenrod;
	unsigned int Magenta;
	unsigned int Antiquewhite;
	unsigned int Cornflowerblue;
	unsigned int Springgreen;
	unsigned int Peru;
	unsigned int Fuchsia;
	unsigned int Papayawhip;
	unsigned int Deepskyblue;
	unsigned int Mediumspringgreen;
	unsigned int Darkgoldenrod;
	unsigned int Violet;
	unsigned int Blanchedalmond;
	unsigned int Lightskyblue;
	unsigned int Lawngreen;
	unsigned int Chocolate;
	unsigned int Plum;
	unsigned int Bisque;
	unsigned int Skyblue;
	unsigned int Chartreuse;
	unsigned int Sienna;
	unsigned int Orchid;
	unsigned int Moccasin;
	unsigned int Lightblue;
	unsigned int Greenyellow;
	unsigned int Saddlebrown;
	unsigned int Mediumorchid;
	unsigned int Navajowhite;
	unsigned int Powderblue;
	unsigned int Lime;
	unsigned int Maroon;
	unsigned int Darkorchid;
	unsigned int Peachpuff;
	unsigned int Paleturquoise;
	unsigned int Limegreen;
	unsigned int Darkred;
	unsigned int Darkviolet;
	unsigned int Mistyrose;
	unsigned int Lightcyan;
	unsigned int Yellowgreen;
	unsigned int Brown;
	unsigned int Darkmagenta;
	unsigned int Lavenderblush;
	unsigned int Cyan;
	unsigned int Darkolivegreen;
	unsigned int Firebrick;
	unsigned int Purple;
	unsigned int Seashell;
	unsigned int Aqua;
	unsigned int Olivedrab;
	unsigned int Indianred;
	unsigned int Indigo;
	unsigned int Oldlace;
	unsigned int Turquoise;
	unsigned int Olive;
	unsigned int Rosybrown;
	unsigned int Darkslateblue;
	unsigned int Ivory;
	unsigned int Mediumturquoise;
	unsigned int Darkkhaki;
	unsigned int Darksalmon;
	unsigned int Blueviolet;
	unsigned int Honeydew;
	unsigned int Darkturquoise;
	unsigned int Palegoldenrod;
	unsigned int Lightcoral;
	unsigned int Mediumpurple;
	unsigned int Mintcream;
	unsigned int Lightseagreen;
	unsigned int Cornsilk;
	unsigned int Salmon;
	unsigned int Slateblue;
	unsigned int Azure;
	unsigned int Cadetblue;
	unsigned int Beige;
	unsigned int Lightsalmon;
	unsigned int Mediumslateblue;
};

#define COLOR_BLACK                0xff000000
#define COLOR_ALICEBLUE            0xfff0f8ff
#define COLOR_DARKCYAN             0xff008b8b
#define COLOR_LIGHTYELLOW          0xffffffe0
#define COLOR_CORAL                0xffff7f50
#define COLOR_DIMGRAY              0xff696969
#define COLOR_LAVENDER             0xffe6e6fa
#define COLOR_TEAL                 0xff008080
#define COLOR_LIGHTGOLDENRODYELLOW 0xfffafad2
#define COLOR_TOMATO               0xffff6347
#define COLOR_GRAY                 0xff808080
#define COLOR_LIGHTSTEELBLUE       0xffb0c4de
#define COLOR_DARKSLATEGRAY        0xff2f4f4f
#define COLOR_LEMONCHIFFON         0xfffffacd
#define COLOR_ORANGERED            0xffff4500
#define COLOR_DARKGRAY             0xffa9a9a9
#define COLOR_LIGHTSLATEGRAY       0xff778899
#define COLOR_DARKGREEN            0xff006400
#define COLOR_WHEAT                0xfff5deb3
#define COLOR_RED                  0xffff0000
#define COLOR_SILVER               0xffc0c0c0
#define COLOR_SLATEGRAY            0xff708090
#define COLOR_GREEN                0xff008000
#define COLOR_BURLYWOOD            0xffdeb887
#define COLOR_CRIMSON              0xffdc143c
#define COLOR_LIGHTGREY            0xffd3d3d3
#define COLOR_STEELBLUE            0xff4682b4
#define COLOR_FORESTGREEN          0xff228b22
#define COLOR_TAN                  0xffd2b48c
#define COLOR_MEDIUMVIOLETRED      0xffc71585
#define COLOR_GAINSBORO            0xffdcdcdc
#define COLOR_ROYALBLUE            0xff4169e1
#define COLOR_SEAGREEN             0xff2e8b57
#define COLOR_KHAKI                0xfff0e68c
#define COLOR_DEEPPINK             0xffff1493
#define COLOR_WHITESMOKE           0xfff5f5f5
#define COLOR_MIDNIGHTBLUE         0xff191970
#define COLOR_MEDIUMSEAGREEN       0xff3cb371
#define COLOR_YELLOW               0xffffff00
#define COLOR_HOTPINK              0xffff69b4
#define COLOR_WHITE                0xffffffff
#define COLOR_NAVY                 0xff000080
#define COLOR_MEDIUMAQUAMARINE     0xff66cdaa
#define COLOR_GOLD                 0xffffd700
#define COLOR_PALEVIOLETRED        0xffdb7093
#define COLOR_SNOW                 0xfffffafa
#define COLOR_DARKBLUE             0xff00008b
#define COLOR_DARKSEAGREEN         0xff8fbc8f
#define COLOR_ORANGE               0xffffa500
#define COLOR_PINK                 0xffffc0cb
#define COLOR_GHOSTWHITE           0xfff8f8ff
#define COLOR_MEDIUMBLUE           0xff0000cd
#define COLOR_AQUAMARINE           0xff7fffd4
#define COLOR_SANDYBROWN           0xfff4a460
#define COLOR_LIGHTPINK            0xffffb6c1
#define COLOR_FLORALWHITE          0xfffffaf0
#define COLOR_BLUE                 0xff0000ff
#define COLOR_PALEGREEN            0xff98fb98
#define COLOR_DARKORANGE           0xffff8c00
#define COLOR_THISTLE              0xffd8bfd8
#define COLOR_LINEN                0xfffaf0e6
#define COLOR_DODGERBLUE           0xff1e90ff
#define COLOR_LIGHTGREEN           0xff90ee90
#define COLOR_GOLDENROD            0xffdaa520
#define COLOR_MAGENTA              0xffff00ff
#define COLOR_ANTIQUEWHITE         0xfffaebd7
#define COLOR_CORNFLOWERBLUE       0xff6495ed
#define COLOR_SPRINGGREEN          0xff00ff7f
#define COLOR_PERU                 0xffcd853f
#define COLOR_FUCHSIA              0xffff00ff
#define COLOR_PAPAYAWHIP           0xffffefd5
#define COLOR_DEEPSKYBLUE          0xff00bfff
#define COLOR_MEDIUMSPRINGGREEN    0xff00fa9a
#define COLOR_DARKGOLDENROD        0xffb8860b
#define COLOR_VIOLET               0xffee82ee
#define COLOR_BLANCHEDALMOND       0xffffebcd
#define COLOR_LIGHTSKYBLUE         0xff87cefa
#define COLOR_LAWNGREEN            0xff7cfc00
#define COLOR_CHOCOLATE            0xffd2691e
#define COLOR_PLUM                 0xffdda0dd
#define COLOR_BISQUE               0xffffe4c4
#define COLOR_SKYBLUE              0xff87ceeb
#define COLOR_CHARTREUSE           0xff7fff00
#define COLOR_SIENNA               0xffa0522d
#define COLOR_ORCHID               0xffda70d6
#define COLOR_MOCCASIN             0xffffe4b5
#define COLOR_LIGHTBLUE            0xffadd8e6
#define COLOR_GREENYELLOW          0xffadff2f
#define COLOR_SADDLEBROWN          0xff8b4513
#define COLOR_MEDIUMORCHID         0xffba55d3
#define COLOR_NAVAJOWHITE          0xffffdead
#define COLOR_POWDERBLUE           0xffb0e0e6
#define COLOR_LIME                 0xff00ff00
#define COLOR_MAROON               0xff800000
#define COLOR_DARKORCHID           0xff9932cc
#define COLOR_PEACHPUFF            0xffffdab9
#define COLOR_PALETURQUOISE        0xffafeeee
#define COLOR_LIMEGREEN            0xff32cd32
#define COLOR_DARKRED              0xff8b0000
#define COLOR_DARKVIOLET           0xff9400d3
#define COLOR_MISTYROSE            0xffffe4e1
#define COLOR_LIGHTCYAN            0xffe0ffff
#define COLOR_YELLOWGREEN          0xff9acd32
#define COLOR_BROWN                0xffa52a2a
#define COLOR_DARKMAGENTA          0xff8b008b
#define COLOR_LAVENDERBLUSH        0xfffff0f5
#define COLOR_CYAN                 0xff00ffff
#define COLOR_DARKOLIVEGREEN       0xff556b2f
#define COLOR_FIREBRICK            0xffb22222
#define COLOR_PURPLE               0xff800080
#define COLOR_SEASHELL             0xfffff5ee
#define COLOR_AQUA                 0xff00ffff
#define COLOR_OLIVEDRAB            0xff6b8e23
#define COLOR_INDIANRED            0xffcd5c5c
#define COLOR_INDIGO               0xff4b0082
#define COLOR_OLDLACE              0xfffdf5e6
#define COLOR_TURQUOISE            0xff40e0d0
#define COLOR_OLIVE                0xff808000
#define COLOR_ROSYBROWN            0xffbc8f8f
#define COLOR_DARKSLATEBLUE        0xff483d8b
#define COLOR_IVORY                0xfffffff0
#define COLOR_MEDIUMTURQUOISE      0xff48d1cc
#define COLOR_DARKKHAKI            0xffbdb76b
#define COLOR_DARKSALMON           0xffe9967a
#define COLOR_BLUEVIOLET           0xff8a2be2
#define COLOR_HONEYDEW             0xfff0fff0
#define COLOR_DARKTURQUOISE        0xff00ced1
#define COLOR_PALEGOLDENROD        0xffeee8aa
#define COLOR_LIGHTCORAL           0xfff08080
#define COLOR_MEDIUMPURPLE         0xff9370db
#define COLOR_MINTCREAM            0xfff5fffa
#define COLOR_LIGHTSEAGREEN        0xff20b2aa
#define COLOR_CORNSILK             0xfffff8dc
#define COLOR_SALMON               0xfffa8072
#define COLOR_SLATEBLUE            0xff6a5acd
#define COLOR_AZURE                0xfff0ffff
#define COLOR_CADETBLUE            0xff5f9ea0
#define COLOR_BEIGE                0xfff5f5dc
#define COLOR_LIGHTSALMON          0xffffa07a
#define COLOR_MEDIUMSLATEBLUE      0xff7b68ee

#endif
